<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.2 on win32)" generated="20200601 15:24:16.823" rpa="false">
<suite id="s1" name="launchApp" source="C:\Users\kchaple\PycharmProjects\Mercury\TestCases\launchApp.robot">
<test id="s1-t1" name="FirstAppium">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>http://localhost:4723/wd/hub</arg>
<arg>platformName=Android</arg>
<arg>platformVersion=9</arg>
<arg>deviceName=Galaxy A10s</arg>
<arg>appPackage=com.capgemini.employeeinfo</arg>
<arg>appActivity=com.capgemini.employeeinfo.LoginActivity</arg>
</arguments>
<msg timestamp="20200601 15:24:20.549" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20200601 15:24:20.550" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20200601 15:24:24.579" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x04811448&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200601 15:24:28.602" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x048114C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200601 15:24:32.616" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x048114F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20200601 15:24:36.649" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200601 15:24:36.632" endtime="20200601 15:24:36.649"></status>
</kw>
<msg timestamp="20200601 15:24:36.651" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200601 15:24:36.666" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x04811598&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20200601 15:24:18.508" endtime="20200601 15:24:36.667"></status>
</kw>
<status status="FAIL" starttime="20200601 15:24:18.507" endtime="20200601 15:24:36.667" critical="yes">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x04811598&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20200601 15:24:16.831" endtime="20200601 15:24:36.668"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="launchApp">launchApp</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200601 15:24:24.579" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x04811448&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200601 15:24:28.602" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x048114C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200601 15:24:32.616" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x048114F0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200601 15:24:36.651" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
